### ISSUE TITLE
Consider new e-skateboard gloves

### ISSUE THREAD

**Issue by Erudition** [wmay/euc-safety#1]
Of the two recommended gloves currently, one of them is fingerless. Flatland 3d makes [a popular fingerless glove](https://flatland3d.com/shop/all-products/all-e-skate-accessories/fingerless-pro-e-skate-glove/) for e-skateboards, but they just came out with a [full-finger version](https://flatland3d.com/shop/all-products/all-e-skate-accessories/carbon-e-skate-glove) as well:

https://flatland3d.com/shop/all-products/all-e-skate-accessories/carbon-e-skate-glove

> Knox patented Scaphoid Protection System (SPS) works to protect your palm and wrist by adding two sliders to the palm of the glove. One of the sliders sits over the general area of the scaphoid, and the second slider acts as a bridge, stopping the grab and twist effect. This system protects the hand from compression fractures and hyper-extension, caused when a typical glove grips the road surface and forward momentum carries the rider’s body over the hand. The SPS sliders now have Knox Micro-Lock impact protection built in, providing the same abrasion resistance as the original, but with additional impact protection.

It has sliders, and a top splint. No bottom splint, but I'm buying these because the two you linked either offer no fingertip protection, no capacitive touch or no top-of-hand protection (and those are thick leather only, and I feel they'll be super hot in summer).

**Comment by wmay** [comment]
Oh cool, thanks. I'll add that. Fun to see companies come out with new stuff
